# DataScience
1. *Data Collection*
2. **Data Cleaning**
3. Data Analysis
4. Data Visualization
5. ## Data Pridection
   1. Machine Learnig
   2. Deep Learning
   3. GanAI
   4. Agentic AI
[click here](https://pypi.org/project/notebook/)
![numpy](https://towardsdatascience.com/wp-content/uploads/2019/12/1cyXCE-JcBelTyrK-58w6_Q.png)

`print("hello world")`
```
if(x < y):
    print("x is less than...")
```

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,5,6,7,8]
myarray1 = np.asarray(mylist, order = 'F')
myarray2 = np.array([7,5,6,8,9,9], order = 'F')

In [3]:
myarray1
# myarray2

array([1, 2, 3, 5, 6, 7, 8])

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(0,1,num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.zeros((3,3),np.float16)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
mylist_m = [[[1],[3],[5]],[[5.0],[8],[9]],[[4],[8],[7]]]
myarray3 = np.array(mylist_m, )

In [9]:
myarray3

array([[[1.],
        [3.],
        [5.]],

       [[5.],
        [8.],
        [9.]],

       [[4.],
        [8.],
        [7.]]])

In [10]:
myarray3.shape

(3, 3, 1)

In [11]:
myarray3.size

9

In [12]:
myarray3.dtype

dtype('float64')

In [13]:
np.random.randint(5,15, size = 10)

array([10,  6, 11, 10,  9, 12, 12, 10,  6,  5], dtype=int32)

In [14]:
np.random.random_sample(10)

array([0.90408619, 0.66712139, 0.73539474, 0.17279647, 0.63514503,
       0.89946326, 0.14481296, 0.44271069, 0.50845782, 0.7214866 ])

In [15]:
np.random.random(10)

array([0.77061333, 0.14379774, 0.84851126, 0.47112449, 0.95160367,
       0.68054595, 0.57821357, 0.89817419, 0.23174371, 0.53887633])

In [16]:
np.random.choice(['T','H',6])

np.str_('6')

In [17]:
mylist_m = [[1,3,5],[5.0,8,9],[4,8,7]]
myarray4 = np.array(mylist_m, )

# How to handle Arrays

In [18]:
myarray1[0:3]

array([1, 2, 3])

In [19]:
myarray4

array([[1., 3., 5.],
       [5., 8., 9.],
       [4., 8., 7.]])

In [20]:
myarray4[:0:-1, ::-1]

array([[7., 8., 4.],
       [9., 8., 5.]])

In [21]:
myarray4[(myarray4%2!=0) | (myarray4 > 5)]

array([1., 3., 5., 5., 8., 9., 8., 7.])

In [22]:
myarray4*2

array([[ 2.,  6., 10.],
       [10., 16., 18.],
       [ 8., 16., 14.]])

In [23]:
myarray4.item(0,1)

3.0

In [24]:
myarray5 = np.array([3,5,7,9,9,4,5,6,4,10])

In [25]:
np.unique(myarray5)

array([ 3,  4,  5,  6,  7,  9, 10])

In [26]:
print(np.unique_counts(myarray5).values)
print(np.unique_counts(myarray5).counts)

[ 3  4  5  6  7  9 10]
[1 2 2 1 1 2 1]


# Reshaping Arrays

In [27]:
print("Myarray5:",myarray5)
myarray6 = myarray5.reshape((5,2))
myarray6

Myarray5: [ 3  5  7  9  9  4  5  6  4 10]


array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [28]:
myarray6.reshape((-1))

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [29]:
myarray7 = np.array([3,5,7,9,9,4,5,6,4,10])
myarray7.resize((5,5))

In [30]:
myarray7

array([[ 3,  5,  7,  9,  9],
       [ 4,  5,  6,  4, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [31]:
myarray6.transpose()

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [32]:
myarray6.swapaxes(1,0)

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [33]:
myarray6

array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [34]:
myarray6.flatten('C')

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [35]:
myarray6.flatten('F')

array([ 3,  7,  9,  5,  4,  5,  9,  4,  6, 10])

In [36]:
myarray7.sort(axis = 1)

In [37]:
myarray7

array([[ 3,  5,  7,  9,  9],
       [ 4,  4,  5,  6, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

# Stacking & Splitting

In [38]:
array1 = np.random.randint(10,size=(3,3))
array2 = np.random.randint(10,size=(3,3))

In [39]:
array3 = np.random.randint(10,size=(3,2))

In [40]:
print("array1:\n",array1)
print("array2:\n",array2)

array1:
 [[7 5 9]
 [4 2 9]
 [4 7 7]]
array2:
 [[2 4 1]
 [8 8 5]
 [1 5 0]]


In [41]:
# np.vstack((array1,array3))
np.hstack((array1,array3))

array([[7, 5, 9, 7, 5],
       [4, 2, 9, 2, 7],
       [4, 7, 7, 8, 8]], dtype=int32)

In [42]:
np.delete(array1,[0,1],0)

array([[4, 7, 7]], dtype=int32)

In [43]:
np.hsplit(array1,(1,2))

[array([[7],
        [4],
        [4]], dtype=int32),
 array([[5],
        [2],
        [7]], dtype=int32),
 array([[9],
        [9],
        [7]], dtype=int32)]

In [44]:
np.vsplit(array1,3)

[array([[7, 5, 9]], dtype=int32),
 array([[4, 2, 9]], dtype=int32),
 array([[4, 7, 7]], dtype=int32)]

# Copying

In [45]:
cp_arr_1 = np.random.randint(10, size=(2, 2))

In [46]:
cp_arr_2 = cp_arr_1

In [47]:
cp_arr_1

array([[6, 5],
       [8, 4]], dtype=int32)

In [48]:
cp_arr_1[0,0] = 2

In [49]:
cp_arr_2

array([[2, 5],
       [8, 4]], dtype=int32)

In [50]:
cp_arr_3 = cp_arr_1.view()

In [51]:
cp_arr_3 += 2

In [52]:
cp_arr_2

array([[ 4,  7],
       [10,  6]], dtype=int32)

In [53]:
cp_arr_4 = cp_arr_1.copy()

In [54]:
cp_arr_4[0,0] = 3

In [55]:
cp_arr_2

array([[ 4,  7],
       [10,  6]], dtype=int32)

# Maths

In [56]:
array1 / 2

array([[3.5, 2.5, 4.5],
       [2. , 1. , 4.5],
       [2. , 3.5, 3.5]])

In [57]:
np.add(array1,2) # array1 + 2
np.subtract(array1,2) # array1 - 2
np.multiply(array1,2) # array1 * 2
np.divide(array1,2) # array1 / 2

array([[3.5, 2.5, 4.5],
       [2. , 1. , 4.5],
       [2. , 3.5, 3.5]])

In [58]:
array1 + array2

array([[ 9,  9, 10],
       [12, 10, 14],
       [ 5, 12,  7]], dtype=int32)

In [59]:
np.random.rand(1,2,4)

array([[[0.37002013, 0.86224482, 0.96049788, 0.7674428 ],
        [0.02360909, 0.93082399, 0.57276787, 0.60100633]]])

In [60]:
print(array1)

[[7 5 9]
 [4 2 9]
 [4 7 7]]


In [83]:
array1.sum(axis = 1)

array([21, 15, 18])

In [62]:
array1.cumsum()

array([ 7, 12, 21, 25, 27, 36, 40, 47, 54])

In [63]:
array1.prod()

np.int64(4445280)

In [64]:
array1.min(axis=0)

array([4, 2, 7], dtype=int32)

In [65]:
array1.max(axis = 1)

array([9, 9, 7], dtype=int32)

In [66]:
array1.argmin(axis = 1)

array([1, 1, 0])

In [67]:
array1.argmax(axis= 0)

array([0, 2, 0])

In [68]:
sortargs = array1.argsort()

In [69]:
array1

array([[7, 5, 9],
       [4, 2, 9],
       [4, 7, 7]], dtype=int32)

In [70]:
for row, args in enumerate(sortargs):
    print(f"Student: {row+1}")
    for column, i in enumerate(args):
        print(f"Rank in subject{column+1} is {i+1}")
    print("*"*10)
        

Student: 1
Rank in subject1 is 2
Rank in subject2 is 1
Rank in subject3 is 3
**********
Student: 2
Rank in subject1 is 2
Rank in subject2 is 1
Rank in subject3 is 3
**********
Student: 3
Rank in subject1 is 1
Rank in subject2 is 2
Rank in subject3 is 3
**********


In [74]:
myarray9 = np.random.randint(10,size=(3,3))
myarray10 = np.random.randint(10,size=(3,3))
print(myarray9,"\n\n",myarray10)

[[0 3 8]
 [7 3 2]
 [6 0 0]] 

 [[3 2 3]
 [5 0 7]
 [1 5 9]]


In [80]:
myarray9[2,2] = -9

In [75]:
np.remainder(myarray9,myarray10) # myarray9 % myarray10

C:\Users\memon\AppData\Local\Temp\ipykernel_18004\1824904202.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.remainder(myarray9,myarray10)


array([[0, 1, 2],
       [2, 0, 2],
       [0, 0, 0]], dtype=int32)

In [77]:
np.power(myarray9, myarray10) # myarray9**2

array([[    0,     9,   512],
       [16807,     1,   128],
       [    6,     0,     0]], dtype=int32)

In [78]:
np.sqrt(myarray9)

array([[0.        , 1.73205081, 2.82842712],
       [2.64575131, 1.73205081, 1.41421356],
       [2.44948974, 0.        , 0.        ]])

In [79]:
np.cbrt(myarray9)

array([[0.        , 1.44224957, 2.        ],
       [1.91293118, 1.44224957, 1.25992105],
       [1.81712059, 0.        , 0.        ]])

In [81]:
np.absolute(myarray9)

array([[0, 3, 8],
       [7, 3, 2],
       [6, 0, 9]], dtype=int32)

In [84]:
studentdata = [["Math","Scince","English","Urdu","Sindhi"],
               [50,60,70,80,40],
               [30,70,80,40,60],
               [20,40,60,80,90],
               [30,60,80,50,40],
               [40,40,30,60,80]]
subject = studentdata.pop(0)

In [85]:
studentdata

[[50, 60, 70, 80, 40],
 [30, 70, 80, 40, 60],
 [20, 40, 60, 80, 90],
 [30, 60, 80, 50, 40],
 [40, 40, 30, 60, 80]]

In [ ]:
# Find Total Obtain Marks
# Find Percentage for every student by (obtain/total)100
# Find Grade on (per>=90 -> A, per>=80 and <90 -> B, per>=70 and <80 -> C, per>=60 and <70 -> D, per<60 -> Fail)
# Assign Ranking on percentage.

In [86]:
std_data = np.array(studentdata)

In [89]:
obtain = std_data.sum(axis=1)

In [137]:
per = obtain / 500 * 100

In [109]:
# grade = np.where(per>=90,'A','B')
# grade = np.where(per>=80,'B',grade)
# grade = np.where(per>=70,'C',grade)
# grade = np.where(per>=60,'D',grade)
# grade = np.where(per<60,'Fail',grade)

In [110]:
# grade

array(['D', 'Fail', 'Fail', 'Fail', 'Fail'], dtype='<U4')

In [138]:
per

array([60., 56., 58., 52., 50.])

In [136]:
# per.sort()
# per[::-1]

In [139]:
rank = per.argsort()[::-1]
rank

array([0, 2, 1, 3, 4])

In [130]:
for r,std in enumerate(rank):
    grade = ''
    if per[std]>= 90:
        grade = 'A'
    elif per[std]>=80 and per[std] <90:
        grade = 'B'
    elif per[std]>=70 and per[std] <80:
        grade = 'C'
    elif per[std]>=60 and per[std] <70:
        grade = 'D'
    else:
        grade = 'Fail'
    print(f"Student no: {std+1}")
    print(f"Rank no:{r+1}")
    print(f"Obtain: {obtain[std]}")
    print(f"Percentage: {per[std]}")
    print(f"Grade: {grade}")
    # print(f"Grade: {grade[std]}")
    print("*"*10)

Student no: 1
Rank no:1
Obtain: 300
Percentage: 60.0
Grade: D
**********
Student no: 3
Rank no:2
Obtain: 290
Percentage: 57.99999999999999
Grade: Fail
**********
Student no: 2
Rank no:3
Obtain: 280
Percentage: 56.00000000000001
Grade: Fail
**********
Student no: 4
Rank no:4
Obtain: 260
Percentage: 52.0
Grade: Fail
**********
Student no: 5
Rank no:5
Obtain: 250
Percentage: 50.0
Grade: Fail
**********


In [140]:
from numpy import genfromtxt

In [155]:
data = genfromtxt("calories.csv",delimiter=',', dtype=str)

In [156]:
header = data[0]
data = data[1:,:]

In [157]:
data

array([['60', '110', '130', '409.1'],
       ['60', '117', '145', '479'],
       ['60', '103', '135', '340'],
       ['45', '109', '175', '282.4'],
       ['45', '117', '148', '406'],
       ['60', '102', '127', '300'],
       ['60', '110', '136', '374'],
       ['40', '104', '134', '253.3'],
       ['30', '109', '133', '195.1'],
       ['60', '98', '124', '269'],
       ['60', '103', '147', '329.3'],
       ['60', '100', '120', '250.7'],
       ['60', '106', '128', '345.3'],
       ['60', '104', '132', '379.3'],
       ['60', '98', '123', '275'],
       ['60', '98', '120', '215.2'],
       ['60', '100', '120', '300'],
       ['45', '90', '112', '200'],
       ['60', '103', '123', '323'],
       ['45', '97', '125', '243'],
       ['60', '108', '131', '364.2'],
       ['45', '100', '119', '282'],
       ['60', '130', '101', '300'],
       ['45', '105', '132', '246'],
       ['60', '102', '126', '334.5'],
       ['60', '100', '120', '250'],
       ['60', '92', '118', '241'],
       ['60'

In [163]:
data = np.array(data,dtype = float)

In [164]:
header

array(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='<U8')

In [165]:
np.mean(data[:,0])

np.float64(63.81656804733728)

In [166]:
np.mean(data[:,3])

np.float64(369.8792899408284)

In [168]:
print(f"Average pulse rate: {np.mean(data[:,2])}")

Average pulse rate: 134.0473372781065


In [179]:
myarray11 = np.random.randint(10,size = 9)
myarray11

array([9, 1, 1, 9, 3, 4, 8, 7, 6], dtype=int32)

In [180]:
myarray11.sort()
myarray11

array([1, 1, 3, 4, 6, 7, 8, 9, 9], dtype=int32)

In [181]:
np.median(myarray11)

np.float64(6.0)