# DataScience
1. *Data Collection*
2. **Data Cleaning**
3. Data Analysis
4. Data Visualization
5. ## Data Pridection
   1. Machine Learnig
   2. Deep Learning
   3. GanAI
   4. Agentic AI
[click here](https://pypi.org/project/notebook/)
![numpy](https://towardsdatascience.com/wp-content/uploads/2019/12/1cyXCE-JcBelTyrK-58w6_Q.png)

`print("hello world")`
```
if(x < y):
    print("x is less than...")
```

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,5,6,7,8]
myarray1 = np.asarray(mylist, order = 'F')
myarray2 = np.array([7,5,6,8,9,9], order = 'F')

In [3]:
myarray1
# myarray2

array([1, 2, 3, 5, 6, 7, 8])

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(0,1,num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.zeros((3,3),np.float16)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
mylist_m = [[[1],[3],[5]],[[5.0],[8],[9]],[[4],[8],[7]]]
myarray3 = np.array(mylist_m, )

In [9]:
myarray3

array([[[1.],
        [3.],
        [5.]],

       [[5.],
        [8.],
        [9.]],

       [[4.],
        [8.],
        [7.]]])

In [10]:
myarray3.shape

(3, 3, 1)

In [11]:
myarray3.size

9

In [12]:
myarray3.dtype

dtype('float64')

In [13]:
np.random.randint(5,15, size = 10)

array([11,  5,  7,  9, 14, 10,  6, 11,  5,  6], dtype=int32)

In [14]:
np.random.random_sample(10)

array([0.52906591, 0.18277119, 0.77050474, 0.02865384, 0.86696944,
       0.92436119, 0.26031277, 0.56097729, 0.11845558, 0.96877013])

In [15]:
np.random.random(10)

array([0.266343  , 0.16433932, 0.46657102, 0.58116275, 0.15531143,
       0.11263156, 0.18108391, 0.63779785, 0.2596892 , 0.39533267])

In [30]:
np.random.choice(['T','H',6])

np.str_('6')

In [16]:
mylist_m = [[1,3,5],[5.0,8,9],[4,8,7]]
myarray4 = np.array(mylist_m, )

# How to handle Arrays

In [17]:
myarray1[0:3]

array([1, 2, 3])

In [18]:
myarray4

array([[1., 3., 5.],
       [5., 8., 9.],
       [4., 8., 7.]])

In [19]:
myarray4[:0:-1, ::-1]

array([[7., 8., 4.],
       [9., 8., 5.]])

In [20]:
myarray4[(myarray4%2!=0) | (myarray4 > 5)]

array([1., 3., 5., 5., 8., 9., 8., 7.])

In [21]:
myarray4*2

array([[ 2.,  6., 10.],
       [10., 16., 18.],
       [ 8., 16., 14.]])

In [24]:
myarray4.item(0,1)

3.0

In [46]:
myarray5 = np.array([3,5,7,9,9,4,5,6,4,10])

In [47]:
np.unique(myarray5)

array([ 3,  4,  5,  6,  7,  9, 10])

In [48]:
print(np.unique_counts(myarray5).values)
print(np.unique_counts(myarray5).counts)

[ 3  4  5  6  7  9 10]
[1 2 2 1 1 2 1]


# Reshaping Arrays

In [74]:
print("Myarray5:",myarray5)
myarray6 = myarray5.reshape((5,2))
myarray6

Myarray5: [ 3  5  7  9  9  4  5  6  4 10]


array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [75]:
myarray6.reshape((-1))

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [101]:
myarray7 = np.array([3,5,7,9,9,4,5,6,4,10])
myarray7.resize((5,5))

In [79]:
myarray7

array([[ 3,  5,  7,  9,  9],
       [ 4,  5,  6,  4, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [81]:
myarray6.transpose()

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [84]:
myarray6.swapaxes(1,0)

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [90]:
myarray6

array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [88]:
myarray6.flatten('C')

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [89]:
myarray6.flatten('F')

array([ 3,  7,  9,  5,  4,  5,  9,  4,  6, 10])

In [104]:
myarray7.sort(axis = 1)

In [105]:
myarray7

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 3,  4,  5,  6,  9],
       [ 4,  5,  7,  9, 10]])

# Stacking & Splitting

In [201]:
array1 = np.random.randint(10,size=(3,3))
array2 = np.random.randint(10,size=(3,3))

In [121]:
array3 = np.random.randint(10,size=(3,2))

In [110]:
print("array1:\n",array1)
print("array2:\n",array2)

array1:
 [[9 7 1]
 [4 6 6]
 [9 2 6]]
array2:
 [[6 6 3]
 [4 9 3]
 [1 2 0]]


In [122]:
# np.vstack((array1,array3))
np.hstack((array1,array3))

array([[9, 7, 1, 3, 2],
       [4, 6, 6, 1, 2],
       [9, 2, 6, 7, 7]], dtype=int32)

In [126]:
np.delete(array1,[0,1],0)

array([[9, 2, 6]], dtype=int32)

In [149]:
np.hsplit(array1,(1,2))

[array([[9],
        [4],
        [9]], dtype=int32),
 array([[7],
        [6],
        [2]], dtype=int32),
 array([[1],
        [6],
        [6]], dtype=int32)]

In [150]:
np.vsplit(array1,3)

[array([[9, 7, 1]], dtype=int32),
 array([[4, 6, 6]], dtype=int32),
 array([[9, 2, 6]], dtype=int32)]

# Copying

In [151]:
cp_arr_1 = np.random.randint(10, size=(2, 2))

In [153]:
cp_arr_2 = cp_arr_1

In [154]:
cp_arr_1

array([[7, 4],
       [5, 6]], dtype=int32)

In [155]:
cp_arr_1[0,0] = 2

In [156]:
cp_arr_2

array([[2, 4],
       [5, 6]], dtype=int32)

In [157]:
cp_arr_3 = cp_arr_1.view()

In [160]:
cp_arr_3 += 2

In [162]:
cp_arr_2

array([[4, 6],
       [7, 8]], dtype=int32)

In [163]:
cp_arr_4 = cp_arr_1.copy()

In [164]:
cp_arr_4[0,0] = 3

In [165]:
cp_arr_2

array([[4, 6],
       [7, 8]], dtype=int32)

# Maths

In [171]:
array1 / 2

array([[4.5, 3.5, 0.5],
       [2. , 3. , 3. ],
       [4.5, 1. , 3. ]])

In [177]:
np.add(array1,2) # array1 + 2
np.subtract(array1,2) # array1 - 2
np.multiply(array1,2) # array1 * 2
np.divide(array1,2) # array1 / 2

array([[4.5, 3.5, 0.5],
       [2. , 3. , 3. ],
       [4.5, 1. , 3. ]])

In [178]:
array1 + array2

array([[15, 13,  4],
       [ 8, 15,  9],
       [10,  4,  6]], dtype=int32)

In [182]:
np.random.rand(1,2,4)

array([[[0.12492184, 0.73474739, 0.71527023, 0.07940948],
        [0.91518925, 0.31947382, 0.60523269, 0.0775088 ]]])

In [184]:
print(array1)

[[9 7 1]
 [4 6 6]
 [9 2 6]]


In [183]:
array1.sum()

np.int64(50)

In [185]:
array1.cumsum()

array([ 9, 16, 17, 21, 27, 33, 42, 44, 50])

In [186]:
array1.prod()

np.int64(979776)

In [194]:
array1.min(axis=0)

array([4, 2, 1], dtype=int32)

In [193]:
array1.max(axis = 1)

array([9, 6, 9], dtype=int32)

In [195]:
array1.argmin(axis = 1)

array([2, 0, 1])

In [196]:
array1.argmax(axis= 0)

array([0, 0, 1])

In [212]:
sortargs = array1.argsort()

ValueError: Cannot specify order when the array has no fields.

In [205]:
array1

array([[0, 6, 3],
       [2, 0, 6],
       [4, 8, 1]], dtype=int32)

In [210]:
for row, args in enumerate(sortargs):
    print(f"Student: {row+1}")
    for column, i in enumerate(args):
        print(f"Rank in subject{column+1} is {i+1}")
    print("*"*10)
        

Student: 1
Rank in subject1 is 1
Rank in subject2 is 3
Rank in subject3 is 2
**********
Student: 2
Rank in subject1 is 2
Rank in subject2 is 1
Rank in subject3 is 3
**********
Student: 3
Rank in subject1 is 3
Rank in subject2 is 1
Rank in subject3 is 2
**********
