# DataScience
1. *Data Collection*
2. **Data Cleaning**
3. Data Analysis
4. Data Visualization
5. ## Data Pridection
   1. Machine Learnig
   2. Deep Learning
   3. GanAI
   4. Agentic AI
[click here](https://pypi.org/project/notebook/)
![numpy](https://towardsdatascience.com/wp-content/uploads/2019/12/1cyXCE-JcBelTyrK-58w6_Q.png)

`print("hello world")`
```
if(x < y):
    print("x is less than...")
```

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,5,6,7,8]
myarray1 = np.asarray(mylist, order = 'F')
myarray2 = np.array([7,5,6,8,9,9], order = 'F')

In [3]:
myarray1
# myarray2

array([1, 2, 3, 5, 6, 7, 8])

In [4]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(0,1,num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.zeros((3,3),np.float16)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
mylist_m = [[[1],[3],[5]],[[5.0],[8],[9]],[[4],[8],[7]]]
myarray3 = np.array(mylist_m, )

In [9]:
myarray3

array([[[1.],
        [3.],
        [5.]],

       [[5.],
        [8.],
        [9.]],

       [[4.],
        [8.],
        [7.]]])

In [10]:
myarray3.shape

(3, 3, 1)

In [11]:
myarray3.size

9

In [12]:
myarray3.dtype

dtype('float64')

In [13]:
np.random.randint(5,15, size = 10)

array([14,  6,  5,  6,  5, 12, 14, 11,  6,  7], dtype=int32)

In [14]:
np.random.random_sample(10)

array([0.90962473, 0.35180273, 0.14984063, 0.94422292, 0.67508242,
       0.46727049, 0.44290205, 0.6954273 , 0.38763641, 0.87415915])

In [15]:
np.random.random(10)

array([0.12566428, 0.41351542, 0.68331686, 0.05615792, 0.70793386,
       0.57393147, 0.44788592, 0.43167301, 0.60382403, 0.76296086])

In [16]:
np.random.choice(['T','H',6])

np.str_('H')

In [17]:
mylist_m = [[1,3,5],[5.0,8,9],[4,8,7]]
myarray4 = np.array(mylist_m, )

# How to handle Arrays

In [18]:
myarray1[0:3]

array([1, 2, 3])

In [19]:
myarray4

array([[1., 3., 5.],
       [5., 8., 9.],
       [4., 8., 7.]])

In [20]:
myarray4[:0:-1, ::-1]

array([[7., 8., 4.],
       [9., 8., 5.]])

In [21]:
myarray4[(myarray4%2!=0) | (myarray4 > 5)]

array([1., 3., 5., 5., 8., 9., 8., 7.])

In [22]:
myarray4*2

array([[ 2.,  6., 10.],
       [10., 16., 18.],
       [ 8., 16., 14.]])

In [23]:
myarray4.item(0,1)

3.0

In [24]:
myarray5 = np.array([3,5,7,9,9,4,5,6,4,10])

In [25]:
np.unique(myarray5)

array([ 3,  4,  5,  6,  7,  9, 10])

In [26]:
print(np.unique_counts(myarray5).values)
print(np.unique_counts(myarray5).counts)

[ 3  4  5  6  7  9 10]
[1 2 2 1 1 2 1]


# Reshaping Arrays

In [27]:
print("Myarray5:",myarray5)
myarray6 = myarray5.reshape((5,2))
myarray6

Myarray5: [ 3  5  7  9  9  4  5  6  4 10]


array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [28]:
myarray6.reshape((-1))

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [29]:
myarray7 = np.array([3,5,7,9,9,4,5,6,4,10])
myarray7.resize((5,5))

In [30]:
myarray7

array([[ 3,  5,  7,  9,  9],
       [ 4,  5,  6,  4, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [31]:
myarray6.transpose()

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [32]:
myarray6.swapaxes(1,0)

array([[ 3,  7,  9,  5,  4],
       [ 5,  9,  4,  6, 10]])

In [33]:
myarray6

array([[ 3,  5],
       [ 7,  9],
       [ 9,  4],
       [ 5,  6],
       [ 4, 10]])

In [34]:
myarray6.flatten('C')

array([ 3,  5,  7,  9,  9,  4,  5,  6,  4, 10])

In [35]:
myarray6.flatten('F')

array([ 3,  7,  9,  5,  4,  5,  9,  4,  6, 10])

In [36]:
myarray7.sort(axis = 1)

In [37]:
myarray7

array([[ 3,  5,  7,  9,  9],
       [ 4,  4,  5,  6, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

# Stacking & Splitting

In [38]:
array1 = np.random.randint(10,size=(3,3))
array2 = np.random.randint(10,size=(3,3))

In [39]:
array3 = np.random.randint(10,size=(3,2))

In [40]:
print("array1:\n",array1)
print("array2:\n",array2)

array1:
 [[9 0 3]
 [0 2 5]
 [2 0 2]]
array2:
 [[9 2 6]
 [4 3 5]
 [4 0 3]]


In [41]:
# np.vstack((array1,array3))
np.hstack((array1,array3))

array([[9, 0, 3, 8, 8],
       [0, 2, 5, 6, 3],
       [2, 0, 2, 7, 6]], dtype=int32)

In [42]:
np.delete(array1,[0,1],0)

array([[2, 0, 2]], dtype=int32)

In [43]:
np.hsplit(array1,(1,2))

[array([[9],
        [0],
        [2]], dtype=int32),
 array([[0],
        [2],
        [0]], dtype=int32),
 array([[3],
        [5],
        [2]], dtype=int32)]

In [44]:
np.vsplit(array1,3)

[array([[9, 0, 3]], dtype=int32),
 array([[0, 2, 5]], dtype=int32),
 array([[2, 0, 2]], dtype=int32)]

# Copying

In [45]:
cp_arr_1 = np.random.randint(10, size=(2, 2))

In [46]:
cp_arr_2 = cp_arr_1

In [47]:
cp_arr_1

array([[7, 1],
       [5, 0]], dtype=int32)

In [48]:
cp_arr_1[0,0] = 2

In [49]:
cp_arr_2

array([[2, 1],
       [5, 0]], dtype=int32)

In [50]:
cp_arr_3 = cp_arr_1.view()

In [51]:
cp_arr_3 += 2

In [52]:
cp_arr_2

array([[4, 3],
       [7, 2]], dtype=int32)

In [53]:
cp_arr_4 = cp_arr_1.copy()

In [54]:
cp_arr_4[0,0] = 3

In [55]:
cp_arr_2

array([[4, 3],
       [7, 2]], dtype=int32)

# Maths

In [56]:
array1 / 2

array([[4.5, 0. , 1.5],
       [0. , 1. , 2.5],
       [1. , 0. , 1. ]])

In [57]:
np.add(array1,2) # array1 + 2
np.subtract(array1,2) # array1 - 2
np.multiply(array1,2) # array1 * 2
np.divide(array1,2) # array1 / 2

array([[4.5, 0. , 1.5],
       [0. , 1. , 2.5],
       [1. , 0. , 1. ]])

In [58]:
array1 + array2

array([[18,  2,  9],
       [ 4,  5, 10],
       [ 6,  0,  5]], dtype=int32)

In [59]:
np.random.rand(1,2,4)

array([[[0.23092637, 0.44832011, 0.27731953, 0.08620383],
        [0.61904801, 0.58816527, 0.52844232, 0.87542134]]])

In [60]:
print(array1)

[[9 0 3]
 [0 2 5]
 [2 0 2]]


In [61]:
array1.sum(axis = 1)

array([12,  7,  4])

In [62]:
array1.cumsum()

array([ 9,  9, 12, 12, 14, 19, 21, 21, 23])

In [63]:
array1.prod()

np.int64(0)

In [64]:
array1.min(axis=0)

array([0, 0, 2], dtype=int32)

In [65]:
array1.max(axis = 1)

array([9, 5, 2], dtype=int32)

In [66]:
array1.argmin(axis = 1)

array([1, 0, 1])

In [67]:
array1.argmax(axis= 0)

array([0, 1, 1])

In [68]:
sortargs = array1.argsort()

In [69]:
array1

array([[9, 0, 3],
       [0, 2, 5],
       [2, 0, 2]], dtype=int32)

In [70]:
for row, args in enumerate(sortargs):
    print(f"Student: {row+1}")
    for column, i in enumerate(args):
        print(f"Rank in subject{column+1} is {i+1}")
    print("*"*10)
        

Student: 1
Rank in subject1 is 2
Rank in subject2 is 3
Rank in subject3 is 1
**********
Student: 2
Rank in subject1 is 1
Rank in subject2 is 2
Rank in subject3 is 3
**********
Student: 3
Rank in subject1 is 2
Rank in subject2 is 1
Rank in subject3 is 3
**********


In [71]:
myarray9 = np.random.randint(10,size=(3,3))
myarray10 = np.random.randint(10,size=(3,3))
print(myarray9,"\n\n",myarray10)

[[9 9 6]
 [7 8 8]
 [1 7 0]] 

 [[3 2 7]
 [8 7 2]
 [2 6 1]]


In [72]:
myarray9[2,2] = -9

In [73]:
np.remainder(myarray9,myarray10) # myarray9 % myarray10

array([[0, 1, 6],
       [7, 1, 0],
       [1, 1, 0]], dtype=int32)

In [74]:
np.power(myarray9, myarray10) # myarray9**2

array([[    729,      81,  279936],
       [5764801, 2097152,      64],
       [      1,  117649,      -9]], dtype=int32)

In [75]:
np.sqrt(myarray9)

C:\Users\memon\AppData\Local\Temp\ipykernel_6460\1949736390.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(myarray9)


array([[3.        , 3.        , 2.44948974],
       [2.64575131, 2.82842712, 2.82842712],
       [1.        , 2.64575131,        nan]])

In [76]:
np.cbrt(myarray9)

array([[ 2.08008382,  2.08008382,  1.81712059],
       [ 1.91293118,  2.        ,  2.        ],
       [ 1.        ,  1.91293118, -2.08008382]])

In [77]:
np.absolute(myarray9)

array([[9, 9, 6],
       [7, 8, 8],
       [1, 7, 9]], dtype=int32)

In [78]:
studentdata = [["Math","Scince","English","Urdu","Sindhi"],
               [50,60,70,80,40],
               [30,70,80,40,60],
               [20,40,60,80,90],
               [30,60,80,50,40],
               [40,40,30,60,80]]
subject = studentdata.pop(0)

In [79]:
studentdata

[[50, 60, 70, 80, 40],
 [30, 70, 80, 40, 60],
 [20, 40, 60, 80, 90],
 [30, 60, 80, 50, 40],
 [40, 40, 30, 60, 80]]

In [80]:
# Find Total Obtain Marks
# Find Percentage for every student by (obtain/total)100
# Find Grade on (per>=90 -> A, per>=80 and <90 -> B, per>=70 and <80 -> C, per>=60 and <70 -> D, per<60 -> Fail)
# Assign Ranking on percentage.

In [81]:
std_data = np.array(studentdata)

In [82]:
obtain = std_data.sum(axis=1)

In [83]:
per = obtain / 500 * 100

In [84]:
# grade = np.where(per>=90,'A','B')
# grade = np.where(per>=80,'B',grade)
# grade = np.where(per>=70,'C',grade)
# grade = np.where(per>=60,'D',grade)
# grade = np.where(per<60,'Fail',grade)

In [85]:
# grade

In [86]:
per

array([60., 56., 58., 52., 50.])

In [87]:
# per.sort()
# per[::-1]

In [88]:
rank = per.argsort()[::-1]
rank

array([0, 2, 1, 3, 4])

In [89]:
for r,std in enumerate(rank):
    grade = ''
    if per[std]>= 90:
        grade = 'A'
    elif per[std]>=80 and per[std] <90:
        grade = 'B'
    elif per[std]>=70 and per[std] <80:
        grade = 'C'
    elif per[std]>=60 and per[std] <70:
        grade = 'D'
    else:
        grade = 'Fail'
    print(f"Student no: {std+1}")
    print(f"Rank no:{r+1}")
    print(f"Obtain: {obtain[std]}")
    print(f"Percentage: {per[std]}")
    print(f"Grade: {grade}")
    # print(f"Grade: {grade[std]}")
    print("*"*10)

Student no: 1
Rank no:1
Obtain: 300
Percentage: 60.0
Grade: D
**********
Student no: 3
Rank no:2
Obtain: 290
Percentage: 57.99999999999999
Grade: Fail
**********
Student no: 2
Rank no:3
Obtain: 280
Percentage: 56.00000000000001
Grade: Fail
**********
Student no: 4
Rank no:4
Obtain: 260
Percentage: 52.0
Grade: Fail
**********
Student no: 5
Rank no:5
Obtain: 250
Percentage: 50.0
Grade: Fail
**********


In [90]:
from numpy import genfromtxt

In [91]:
data = genfromtxt("calories.csv",delimiter=',', dtype=str)

In [92]:
header = data[0]
data = data[1:,:]

In [93]:
data

array([['60', '110', '130', '409.1'],
       ['60', '117', '145', '479'],
       ['60', '103', '135', '340'],
       ['45', '109', '175', '282.4'],
       ['45', '117', '148', '406'],
       ['60', '102', '127', '300'],
       ['60', '110', '136', '374'],
       ['40', '104', '134', '253.3'],
       ['30', '109', '133', '195.1'],
       ['60', '98', '124', '269'],
       ['60', '103', '147', '329.3'],
       ['60', '100', '120', '250.7'],
       ['60', '106', '128', '345.3'],
       ['60', '104', '132', '379.3'],
       ['60', '98', '123', '275'],
       ['60', '98', '120', '215.2'],
       ['60', '100', '120', '300'],
       ['45', '90', '112', '200'],
       ['60', '103', '123', '323'],
       ['45', '97', '125', '243'],
       ['60', '108', '131', '364.2'],
       ['45', '100', '119', '282'],
       ['60', '130', '101', '300'],
       ['45', '105', '132', '246'],
       ['60', '102', '126', '334.5'],
       ['60', '100', '120', '250'],
       ['60', '92', '118', '241'],
       ['60'

In [94]:
data = np.array(data,dtype = float)

In [95]:
header

array(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='<U8')

In [96]:
np.mean(data[:,0])

np.float64(63.81656804733728)

In [97]:
np.mean(data[:,3])

np.float64(369.8792899408284)

In [98]:
print(f"Average pulse rate: {np.mean(data[:,2])}")

Average pulse rate: 134.0473372781065


In [99]:
myarray11 = np.random.randint(10,size = 9)
myarray11

array([9, 3, 6, 6, 6, 8, 4, 9, 4], dtype=int32)

In [100]:
myarray11.sort()
myarray11

array([3, 4, 4, 6, 6, 6, 8, 9, 9], dtype=int32)

In [101]:
np.median(myarray11)

np.float64(6.0)

## An online store records daily sales (in dollars) for 3 products over 7 days.
# Tasks
1. Find total weekly sales for each product.
2. Find the day with the highest overall sales.
3. Calculate average daily sales across all products.
4. Identify products whose weekly sales exceed $1000.
5. Apply a 10% discount to all sales values greater than 200.

In [102]:
import numpy as np
sales = np.array([
    [120, 150, 180, 200, 170, 190, 210],  # Product A
    [80, 90, 100, 110, 95, 105, 115],     # Product B
    [200, 220, 210, 230, 240, 250, 260]   # Product C
])

In [153]:
weekly_sales_prod = sales.sum(axis = 1)
daily_sales = sales.sum(axis = 0)
highest_sales_day = daily_sales.argmax()+1
prod_average_sales = sales.mean(axis=1)
prod_sales_1000 = np.where(weekly_sales_prod > 1000)
discounted = np.where(sales > 200, sales - (sales * 0.1), sales)

In [155]:
print(f"Weekly sales per prod: {weekly_sales_prod}")
print(f"Highest sales on day {highest_sales_day}")
print(f"Average daily sales per prod: {prod_average_sales}")
print(f"Prod with weekly sales exceeded by 1000$ : {prod_sales_1000[0]+1}")
print(discounted)

Weekly sales per prod: [1220  695 1610]
Highest sales on day 7
Average daily sales per prod: [174.28571429  99.28571429 230.        ]
Prod with weekly sales exceeded by 1000$ : [1 3]
[[120. 150. 180. 200. 170. 190. 189.]
 [ 80.  90. 100. 110.  95. 105. 115.]
 [200. 198. 189. 207. 216. 225. 234.]]


## An investor starts with an initial investment of $5000. The yearly profit/loss percentages for the next 5 years are:
# Tasks
1. Convert the profit/loss percentages into growth factors.
    1. Example: 20% → 1.20, -20% → 0.80
2. Calculate the investment value at the end of each year.
3. Find the total profit or loss amount after 5 years.
4. Calculate the overall profit/loss percentage relative to the initial investment.
5. Determine:
    1. Which year had the highest growth?
    2. Which year had the biggest loss?
6. Create an array showing the profit/loss amount earned in each year.
   
- Expected Result
- Year-end values:
- Year 1: 6000
- Year 2: 7800
- Year 3: 8580
- Year 4: 6864
- Year 5: 6177.60
- Final investment value: 6177.60
- Total profit: 1177.60
- Overall return: 23.55%

In [111]:
import numpy as n
initial_investment = 5000
profit_percent = np.array([20, 30, 10, -20, -10])

In [112]:
g_factor = (profit_percent / 100) +1
g_factor

array([1.2, 1.3, 1.1, 0.8, 0.9])

In [134]:
profit_factor = g_factor.cumprod()
profit_factor

array([1.2    , 1.56   , 1.716  , 1.3728 , 1.23552])

In [136]:
yearly_investment = profit_factor * initial_investment
yearly_investment

array([6000. , 7800. , 8580. , 6864. , 6177.6])

In [139]:
profit_year5 = yearly_investment[-1] - initial_investment
profit_year5

np.float64(1177.6000000000013)

In [141]:
total_profit_per = profit_year5 / initial_investment * 100

In [148]:
print("Year End Values:")
for index, value in enumerate(yearly_investment):
    print(f"Year {index+1}: {value}")
print(f"final investment value: {yearly_investment[-1]}")
print(f"final profit: {profit_year5}")
print(f"Overall returns: {total_profit_per}")

Year End Values:
Year 1: 6000.0
Year 2: 7800.0
Year 3: 8580.000000000002
Year 4: 6864.000000000001
Year 5: 6177.600000000001
final investment value: 6177.600000000001
final profit: 1177.6000000000013
Overall returns: 23.552000000000024


In [160]:
data = np.array([["std1","yasir1",50,70,80],
                 ["std2","yasir2",50,70,80],
                 ["std3","yasir3",50,70,80]], dtype = np.float64)

ValueError: could not convert string to float: 'std1'

In [157]:
data

array([['std1', 'yasir1', '50', '70', '80'],
       ['std2', 'yasir2', '50', '70', '80'],
       ['std3', 'yasir3', '50', '70', '80']], dtype='<U21')