# DataScience
1. *Data Collection*
2. **Data Cleaning**
3. Data Analysis
4. Data Visualization
5. ## Data Pridection
   1. Machine Learnig
   2. Deep Learning
   3. GanAI
   4. Agentic AI
[click here](https://pypi.org/project/notebook/)
![numpy](https://towardsdatascience.com/wp-content/uploads/2019/12/1cyXCE-JcBelTyrK-58w6_Q.png)

`print("hello world")`
```
if(x < y):
    print("x is less than...")
```

In [1]:
import numpy as np

In [22]:
mylist = [1,2,3,5,6,7,8]
myarray1 = np.asarray(mylist, order = 'F')
myarray2 = np.array([7,5,6,8,9,9], order = 'F')

In [24]:
myarray1
# myarray2

array([1, 2, 3, 5, 6, 7, 8])

In [28]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [29]:
np.linspace(0,1,num = 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [32]:
np.zeros((3,3),np.float16)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
mylist_m = [[[1],[3],[5]],[[5.0],[8],[9]],[[4],[8],[7]]]
myarray3 = np.array(mylist_m, )

In [62]:
myarray3

array([[[1.],
        [3.],
        [5.]],

       [[5.],
        [8.],
        [9.]],

       [[4.],
        [8.],
        [7.]]])

In [63]:
myarray3.shape

(3, 3, 1)

In [64]:
myarray3.size

9

In [65]:
myarray3.dtype

dtype('float64')

In [80]:
np.random.randint(5,15, size = 10)

array([13,  9, 11, 10, 10, 13, 12, 13, 12, 12], dtype=int32)

In [89]:
np.random.random_sample(10)

array([0.19562423, 0.68700472, 0.20963156, 0.78439511, 0.52019205,
       0.16337865, 0.76021215, 0.94736529, 0.28661414, 0.70283603])

In [90]:
np.random.random(10)

array([0.86643869, 0.00887775, 0.12020631, 0.14977574, 0.0777271 ,
       0.60727765, 0.65579447, 0.9282857 , 0.73283675, 0.05629819])

In [92]:
mylist_m = [[1,3,5],[5.0,8,9],[4,8,7]]
myarray4 = np.array(mylist_m, )

# How to handle Arrays

In [99]:
myarray1[0:3]

array([1, 2, 3])

In [100]:
myarray4

array([[1., 3., 5.],
       [5., 8., 9.],
       [4., 8., 7.]])

In [113]:
myarray4[:0:-1, ::-1]

array([[7., 8., 4.],
       [9., 8., 5.]])

In [121]:
myarray4[(myarray4%2!=0) | (myarray4 > 5)]

array([1., 3., 5., 5., 8., 9., 8., 7.])

In [116]:
myarray4*2

array([[ 2.,  6., 10.],
       [10., 16., 18.],
       [ 8., 16., 14.]])