# DataScience
1. *Data Collection*
2. **Data Cleaning**
3. Data Analysis
4. Data Visualization
5. ## Data Pridection
   1. Machine Learnig
   2. Deep Learning
   3. GanAI
   4. Agentic AI
[click here](https://pypi.org/project/notebook/)
![numpy](https://towardsdatascience.com/wp-content/uploads/2019/12/1cyXCE-JcBelTyrK-58w6_Q.png)

`print("hello world")`
```
if(x < y):
    print("x is less than...")
```

In [1]:
import numpy as np

In [19]:
list_1 = [1, 2, 3, 4, 5]
m_list_1 = [[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]]
myarray = np.array(list_1)
myarray1 = np.array([4,5,6,3,5,6,7])
myarray2 = np.array(m_list_1)

In [20]:
myarray
myarray1
myarray2

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [23]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.linspace(1,10,num=100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
myarray2.shape

(3, 3, 1)

In [31]:
myarray2.size

9